version: "3.8"

services:
  nginx:
    working_dir: /app
    image: "nginx:1.17.10-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    image: "gavinpalmer/watch-party:latest"
    environment:
      ADMIN_PASSWORD: ${PORTAL_WATCH_PARTY_ADMIN_PASSWORD}
      YOUTUBE_API_KEY: ${PORTAL_WATCH_PARTY_YOUTUBE_API_KEY}
    volumes:
      - ./server/api/party_info/data.json:/app/api/party_info/data.json
